{"name": "Неудачный вход в систему для существующего пользователя с неверными данными", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "user_login_data_json", "value": "{'email': 'INc0RR3CT_email5125@yandex.ru', 'password': 'ehugtiwmqk'}"}], "start": 1736340091569, "stop": 1736340091763}], "parameters": [{"name": "field_name", "value": "'email'"}, {"name": "field_value", "value": "'INc0RR3CT_email5125@yandex.ru'"}], "start": 1736340091569, "stop": 1736340091763, "uuid": "41ca212d-a13a-4b9c-8ff8-a90ecb153160", "historyId": "36ac1d62ec67059981d80b55d608d05b", "testCaseId": "88a6f8856dc37b2b144fff9c955f564b", "fullName": "tests.auth.test_user_login.TestUserLogin#test_login_by_existing_user_with_incorrect_data_returns_error", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-2S7589E"}, {"name": "thread", "value": "2324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_user_login"}]}